from django.contrib import admin
from .models import *
admin.site.register(xiangmu)
admin.site.register(cdn)
admin.site.register(huanjing)
admin.site.register(suoshuyewu)
admin.site.register(yuming)
admin.site.register(beian)
admin.site.register(yumingzhuangtai)
admin.site.register(jxs)
admin.site.register(ywlx)
admin.site.register(username)
admin.site.register(uhistory)
admin.site.register(acmessl)
admin.site.register(icp)
admin.site.register(domain_expire)
admin.site.register(apollo)
admin.site.register(apollo_history)
admin.site.register(ck)
admin.site.register(game_id)
admin.site.register(upload_switch)
admin.site.register(aws_waf_history)